ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
    - id: clang-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
